version: '2'
services:
  web:
    build: iconserver/
    ports:
      - "8083:80"
    networks:
      ssrf:
        ipv4_address: 172.16.1.2
  secret:
    build: secretserver/
    networks:
      ssrf:
        ipv4_address: 172.16.1.4
networks:
  ssrf:
    ipam:
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
